spring:
   datasource:
      name: crm
      url: jdbc:mysql://localhost:3306/elec-product?useUnicode=true&characterEncoding=UTF8&useSSL=false
      username: ENC(9397CYXMXkHpb5TVl6FlPw==)
      password: ENC(xQWl6FxysKQYa+flq+EwVg==)
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
   jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
feign:  
  hystrix:  
    enabled: true
ribbon:
  ReadTimeout: 500
  ConnectTimeout: 500
  # 关闭Ribbon的重试机制
  MaxAutoRetriesNextServer: 0
  
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
        #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 500

#如果想对单独的某个服务进行详细配置，如下
#poc-customer-service:
#  ribbon:
#    connectTimeout: 5000

redis:
    pool:
         maxActive: 300
         maxIdle: 100
         maxWait: 1000
    host: localhost
    port: 6379
    password:
    timeout: 2000
    # 服务或应用名
    sysName: auth-service
    enable: true
    database: 0
  
logging:
  level:
    com.poc: DEBUG
    jdbc.audit: INFO
    jdbc.resultset: INFO
    jdbc.sqlonly: INFO
    jdbc.sqltiming: INFO
    jdbc.connection: INFO

# tx-lcn分布式事务参数表
tx-lcn:
  ribbon:
    loadbalancer:
      dtx:
      # 是否启动LCN负载均衡策略(优化选项，开启与否，功能不受影响)
        enabled: true
  client:
# tx-manager 的配置地址，可以指定TM集群中的任何一个或多个地址
# tx-manager 下集群策略，每个TC都会从始至终<断线重连>与TM集群保持集群大小个连接。
# TM方，每有TM进入集群，会找到所有TC并通知其与新TM建立连接。
# TC方，启动时按配置与集群建立连接，成功后，会再与集群协商，查询集群大小并保持与所有TM的连接
    manager-address: 127.0.0.1:8070
    # 调用链长度等级，默认值为3（优化选项。系统中每个请求大致调用链平均长度，估算值。）
    chain-level: 3
    # 该参数为tc与tm通讯时的最大超时时间，单位ms。该参数不需要配置会在连接初始化时由tm返回。
    tm-rpc-timeout: 2000
    # 该参数为事务方法注解切面的orderNumber，默认值为0.
    dtx-aspect-order: 0
    # 该参数为事务连接资源方法切面的orderNumber，默认值为0.
    resource-order: 0
  #aspect:
    #log:
    # 该参数是分布式事务框架存储的业务切面信息。采用的是h2数据库。绝对路径。该参数默认的值为{user.dir}/.txlcn/{application.name}-{application.port}
     # file-path: ../logs/.txlcn/{application.name}-{application.port}