filter:
   ignore-uri: /api/login,/api/logout,/api/static,/api/sendMobileCode,/api/varifyMObileCode

zuul:
  host:
    maxTotalConnections: 2048
    maxPerRouteConnections: 1024
  routes:
    poc-auth-service:
      path: /auth/**
      serviceId: poc-auth-service
    poc-order-service:
      path: /order/**
      serviceId: poc-order-service
    poc-product-service1:
          path: /product/**
          serviceId: poc-product-service
    poc-product-service2:
      path: /plan/**
      serviceId: poc-product-service
    poc-product-service3:
          path: /discount/**
          serviceId: poc-product-service
    poc-promotion-service:
      path: /promotion/**
      serviceId: poc-promotion-service
    poc-payment-service:
      path: /payment/**
      serviceId: poc-payment-service
    poc-customer-service:
      path: /customer/**
      serviceId: poc-customer-service
    #poc-admin-service:
      #path: /admin/**
      #serviceId: poc-admin-service
eureka:
  client:
    healthcheck:
      enabled: true

feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 2000
  ConnectTimeout: 2000
  # 关闭Ribbon的重试机制
  MaxAutoRetriesNextServer: 0
  
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
        #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 2000

#如果想对单独的某个服务进行详细配置，如下
#poc-customer-service:
#  ribbon:
#    connectTimeout: 5000

logging:
  level:
    com.poc: INFO
    jdbc.audit: ERROR
    jdbc.resultset: ERROR
    jdbc.sqlonly: ERROR

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
