filter:
   ignore-uri: /api/login,/api/logout,/api/static,/api/sendMobileCode,/api/varifyMObileCode

zuul:
  #hystrix信号量semaphore的设置，默认为100，决定了hystrix并发请求数 tomcat线程池默认是200
  semaphore:
    max-semaphores: 500
  host:
    maxTotalConnections: 2048
    maxPerRouteConnections: 1024
  routes:
    poc-auth-service:
      path: /auth/**
      serviceId: poc-auth-service
    poc-order-service:
      path: /order/**
      serviceId: poc-order-service
    poc-product-service1:
      path: /product/**
      serviceId: poc-product-service
    poc-promotion-service:
      path: /promotion/**
      serviceId: poc-promotion-service
    poc-payment-service:
      path: /payment/**
      serviceId: poc-payment-service
    poc-customer-service:
      path: /customer/**
      serviceId: poc-customer-service
    #poc-admin-service:
      #path: /admin/**
      #serviceId: poc-admin-service

ribbon:
  #Ribbon允许最大连接数，即所有后端微服务实例请求并发数之和的最大值。
  MaxTotalConnections: 500
  #单个后端微服务实例能接收的最大请求并发数  
  MaxConnectionsPerHost: 500
  ReadTimeout: 1000
  ConnectTimeout: 1000
  # 关闭Ribbon的重试机制
  MaxAutoRetriesNextServer: 1
  
#hystrix 配置
hystrix:
  threadpool:
    default:
      coreSize: 50
  command:
    default:
      #fallback:
        #isolation:
          #semaphore:
            #maxConcurrentRequests: 50
      execution:
        timeout:
        #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 4000

#如果想对单独的某个服务进行详细配置，如下
#poc-customer-service:
#  ribbon:
#    connectTimeout: 5000
 
logging:
  level:
    com.poc: DEBUG
    jdbc.audit: ERROR
    jdbc.resultset: ERROR
    jdbc.sqlonly: ERROR

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
